apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.global.istio.gateway.udm }}
spec:
  selector:
    istio: {{ .Values.global.istio.gateway.istio }}
  servers:
  - port:
      number: {{ .Values.global.istio.gateway.port }}
      name: http2
      protocol: HTTP2
    hosts:
    - "*"