apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.global.istio.gateway.udm }}
  http:
  - match:
    - uri:
        regex: "^/nudm-ee/v1/.*$"
      method:
        exact: "POST"
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ .Values.service.name }}
