version: '3'
services:
    dbproxyhttp2:
       image: "dbproxyhttp2:latest"
       links:
           - "udrsim"
       ports:
           - "9084:9084"
       networks:
           backend:
             ipv4_address: 172.16.238.4
       environment:
           - DBPROXY2PORT=9084
    udrsim:
        image: "udrsim:latest"
        ports:
            - "9082:9082"
        networks:
            backend:
              ipv4_address: 172.16.238.2
        environment:
            - UDRPORT=9082
            - TLSENABLED=1
            - LOGLEVEL=7
            - HEADERCHECK=1            
networks:
    backend:
        driver: "bridge"
        ipam:
           driver: "default"
           config:
               - subnet: "172.16.238.0/24"
    # dbproxyhttp2:
    #     image: "dbproxyhttp2:latest"
    #     ports:
    #         - "9084:9084"
    #     networks:
    #         backend:
    #           ipv4_address: 172.16.238.10
    #     environment:
    #         - DBPROXY2PORT=9084