apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dbproxyhttp2-circuitbreaker
spec:
  host: dbproxyhttp2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1500
      http:
         http2MaxRequests: 15000
         maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 1
      interval: 2s
      baseEjectionTime: 1m
      maxEjectionPercent: 50