apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: eecreatesubscription-circuitbreaker
spec:
  host: eecreatesubscription
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
         http2MaxRequests: 10000
         maxRequestsPerConnection: 100
         maxRetries: 300
    outlierDetection:
      consecutiveErrors: 250
      interval: 10s
      baseEjectionTime: 1m
      maxEjectionPercent: 100