apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dbproxyhttp2-circuitbreaker
spec:
  host: dbproxyhttp2
  trafficPolicy:
    # connectionPool:
    #   tcp:
    #     maxConnections: 1000
    #   http:
    #      http2MaxRequests: 10000
    #      maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 3
      interval: 10s
      baseEjectionTime: 1m
      maxEjectionPercent: 80