apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: udrsim
spec:
  hosts:
  - "*"
  gateways:
  - eric-udm-gateway
  http:
  - match:
    - uri:
        regex: "^/nudr-dr/v1/.*$"
      method:
        regex: "^(POST|GET|DELETE|PUT)$"
    route:
    - destination:
        port:
          number: 9082
        host: udrsim
    retries:
      attempts: 15
      perTryTimeout: 1s