apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eecreatesubscription
spec:
  hosts:
  - "*"
  gateways:
  - eric-udm-gateway
  http:
  - match:
    - uri:
        regex: "^/nudm-ee/v1/.*$"
      method:
        regex: "^(POST|GET|DELETE|PUT)$"
    route:
    - destination:
        port:
          number: 9002
        host: eecreatesubscription
    retries:
      attempts: 30
      perTryTimeout: 1s